# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: andmorefine
# "service" is the name of this project. This will also be added to your AWS resource names.
service: node-http-api

provider:
  name: aws
  stage: beta
  region: ap-northeast-1
  profile: severless
  runtime: nodejs20.x
  environment:
    MAILUSER: ${param:user}
    MAILPASSWORD: ${param:password}
    TOMAIL: ${param:tomail}

# serverless deploy --param="user=xxx" --param="password=xxx" --param="tomail=xxx"

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  sendemail:
    handler: handler.sendemail
    events:
      - httpApi:
          path: /sendemail
          method: post
